### PR TITLE
Location Doctype: Add link to IT Objects List with filter

### LINKED ISSUE #33: improve Location Doctype
- I would like to have a dashboard, were we can see which doctypes (Starting with IT Object) are linked to a specific location.
- but i think this would not work recursive. How can we check/display which objects are linked to a location and its childs?

### PR DESCRIPTION
**Pull request by jordialbert**
Closes #33 

Add a custom button which displays the IT Objects List filtered by the location and its child locations.

### CODE REVIEW

File: msp/public/js/location.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+frappe.ui.form.on('Location', {
+    refresh(frm) {
+        frm.add_custom_button('Show IT Objects in Location', () => {
+            frappe.set_route('List', 'IT Object', { location_full_path: ['like', `%${frm.doc.location_name}%`] })
```
Comment (itsdaveit) [inline msp/public/js/location.js]: Will this work? What happens, if we have multipe Locations with the same name?

Comment (itsdaveit) [reply msp/public/js/location.js]: I think we have to determinate all child locations and use an "in" Filter?

Comment (jordialbert) [reply msp/public/js/location.js]: You are right, now it is filtered with an 'IN' where clause and with all the child locations for the particular location.
